require:
  - solidus_dev_support/rubocop

AllCops:
  NewCops: disable


RSpec/MultipleExpectations:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/LetSetup:
  Enabled: false
